# Generated by Django 3.2.6 on 2021-08-07 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mostrar_html', '0002_dojo_ninja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wizard',
            name='last_name',
        ),
    ]
